### ISSUE TITLE
Add more variables other than primary-color

### ISSUE THREAD

**Issue by Vandenberg** [luffyZh/dynamic-antd-theme#22]
Would it be a good idea to add other variables to the configuration? As far as I can tell you can only change the main color, but it would be worth adding options for warning and success colors, border-radius, active-color etc. I see there's a similar thread on this but sadly I don't speak mandarin :(

**Comment by FrenchMajesty** [comment]
There is also an issue with the different "shades" of the primary color not being applied on `antd@4.20.0`.

For example `Input` glow on focus does not get updated.

**Comment by wuzekang** [comment]
@Vandenberg you can try this https://www.npmjs.com/package/antd-theme

**Comment by luffyZh** [comment]
@Vandenberg I understand what you mean, but there are many mature schemes available in the community, such as antd-theme-generator, such as the upstairs antd-theme, which are excellent libs, so I didn't make it so complicated.

**Comment by FrenchMajesty** [comment]
@luffyZh What about the different shades of color? I've looked into those other libraries but they do not serve the purpose I need because they are not dynamic.

My use case:
I have a multi-tenant application and I want each web portal to be branded to the business.

when URL `businessName.mydomain.com` is hit, we make API request to load information about `businessName` and then we apply the color of that given tenant to to the entire React app frontend.

Anything other than the dynamism I get from this library wouldn't work. It also wouldn't be a necessarily hard fix. There are many ways in JS (or .less) to get a derived color. More css variables could be created for them and then used to ovverride default values.

Or you could do what I've done which is set the colors of all `box-shadow` to light gray and then update the `border-color`. 

<img width="317" alt="Screen Shot 2020-05-31 at 1 55 17 AM" src="https://user-images.githubusercontent.com/24761660/83346417-ca15f780-a2e1-11ea-80d3-3a8e5a8a322c.png">

This at least a much better UI to have instead of one with conflicting colors.

**Comment by luffyZh** [comment]
@FrenchMajesty 

Thank you for your attention and for using this lib,I understand your problem. Since the antd 4.0 update, the className of many components have changed, resulting in mismatches in some styles. I will always find the problem and update them. Welcome to continue using and feedback.

![图片](https://user-images.githubusercontent.com/17840558/83382708-51fd1e00-a416-11ea-9ca2-d22be0661d4f.png)

![图片](https://user-images.githubusercontent.com/17840558/83382736-5e817680-a416-11ea-8bb3-919d85ce973f.png)

The above screenshot is a fix for the style of `input:focus`, and the rest will continue to be updated，current version `0.6.1`
